### PR TITLE
add delivery config

### PR DESCRIPTION
**Pull request by afiune**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by afiune** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Failed to approve change: d8ddcc65-dbb0-4d5d-90c5-5575ea3a64d0 @afiune

**Comment by dmccown** [comment]
:+1:

**Comment by afiune** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Failed to approve change: d8ddcc65-dbb0-4d5d-90c5-5575ea3a64d0 @afiune

**Comment by afiune** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: d8ddcc65-dbb0-4d5d-90c5-5575ea3a64d0 approved by: @afiune

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
